import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiFirebase,
  SiPython,
  SiCplusplus,
  SiGit,
  SiGithub,
  SiPostman,
  SiFigma,
  SiGoogleanalytics,
  SiGoogleads,
  SiMeta,
  SiVscodium,
  SiCanva,
  SiOpenai,
  SiLangchain,
  SiHuggingface,
  SiVercel,
  SiAnthropic,
} from "react-icons/si";

export const skillIconMap: Record<string, { Icon: IconType; color: string }> = {
  // Frontend
  React: { Icon: SiReact, color: "#61DAFB" },
  "React.js": { Icon: SiReact, color: "#61DAFB" },
  "Next.js": { Icon: SiNextdotjs, color: "currentColor" },
  TypeScript: { Icon: SiTypescript, color: "#3178C6" },
  JavaScript: { Icon: SiJavascript, color: "#F7DF1E" },
  HTML5: { Icon: SiHtml5, color: "#E34F26" },
  CSS3: { Icon: SiCss, color: "#1572B6" },
  "Tailwind CSS": { Icon: SiTailwindcss, color: "#06B6D4" },
  // Backend
  "Node.js": { Icon: SiNodedotjs, color: "#339933" },
  "Express.js": { Icon: SiExpress, color: "currentColor" },
  Express: { Icon: SiExpress, color: "currentColor" },
  // Database
  MongoDB: { Icon: SiMongodb, color: "#47A248" },
  Firebase: { Icon: SiFirebase, color: "#FFCA28" },
  // AI
  "OpenAI API": { Icon: SiOpenai, color: "currentColor" },
  OpenAI: { Icon: SiOpenai, color: "currentColor" },
  LangChain: { Icon: SiLangchain, color: "#1C3C3C" },
  "Hugging Face": { Icon: SiHuggingface, color: "#FF9D00" },
  "Vercel AI SDK": { Icon: SiVercel, color: "currentColor" },
  Anthropic: { Icon: SiAnthropic, color: "currentColor" },
  // Other
  Python: { Icon: SiPython, color: "#3776AB" },
  "C++": { Icon: SiCplusplus, color: "#00599C" },
  Git: { Icon: SiGit, color: "#F05032" },
  GitHub: { Icon: SiGithub, color: "currentColor" },
  Postman: { Icon: SiPostman, color: "#FF6C37" },
  "VS Code": { Icon: SiVscodium, color: "#2F80ED" },
  Figma: { Icon: SiFigma, color: "#F24E1E" },
  "Google Analytics": { Icon: SiGoogleanalytics, color: "#E37400" },
  "Google Ads": { Icon: SiGoogleads, color: "#4285F4" },
  "Meta Ads": { Icon: SiMeta, color: "#0082FB" },
  "Social Media Marketing": { Icon: SiMeta, color: "#0082FB" },
  Canva: { Icon: SiCanva, color: "#00C4CC" },
};

export type SkillIconEntry = { Icon: IconType; color: string };
